export type Vector = number[]
export type Vector2 = [number, number]
export type Vector3 = [number, number, number]
export type Quaternion = [number, number, number, number]
export type Vector7 = [number, number, number, number, number, number, number]
