import { html } from "@inglorious/web"

export const about = {
  render() {
    return html`
      <div>
        <h1>About</h1>
        <p>This is a static page generated by SSX.</p>
        <a href="/">Back Home</a>
      </div>
    `
  },
}

export const metadata = {
  title: "About",
}
